title: Test site 3 columns
email: xitricite@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/site" # the subpath of your site, e.g. /blog
url: "https://xitricite.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: xitricite
github_username:  xitricite

#Custom settings
rss-show: 0 #0 is false, turn off feed
header-logo: '/assets/nothing_logo.png' #enter path

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
